// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Client.Models.Apartamento", b =>
                {
                    b.Property<long>("UnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("unidadid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnidadId"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("area");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<int>("TorreId")
                        .HasColumnType("int")
                        .HasColumnName("torreid");

                    b.HasKey("UnidadId");

                    b.ToTable("apartamentos", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.BitacoraVigilancia", b =>
                {
                    b.Property<long>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("bitacoraid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BitacoraId"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechahora");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion");

                    b.Property<int>("VigilanteId")
                        .HasColumnType("int")
                        .HasColumnName("vigilanteid");

                    b.HasKey("BitacoraId");

                    b.ToTable("bitacoravigilancia", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Conjunto", b =>
                {
                    b.Property<long>("ConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("conjuntoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConjuntoId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.HasKey("ConjuntoId");

                    b.ToTable("conjunto", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Ingreso", b =>
                {
                    b.Property<long>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ingresoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngresoId"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("documento");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechahoraingreso");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechahorasalida");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombrepersona");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidadid");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioid");

                    b.HasKey("IngresoId");

                    b.ToTable("ingreso", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Mantenimiento", b =>
                {
                    b.Property<long>("MantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mantenimientoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MantenimientoId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("proveedor");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("int")
                        .HasColumnName("tipomantenimientoid");

                    b.Property<int>("ZonaComunId")
                        .HasColumnType("int")
                        .HasColumnName("zonacomunid");

                    b.HasKey("MantenimientoId");

                    b.ToTable("mantenimiento", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Parqueadero", b =>
                {
                    b.Property<long>("ParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("parqueaderoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParqueaderoId"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidadid");

                    b.HasKey("ParqueaderoId");

                    b.ToTable("parqueadero", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.ParqueaderoVisitante", b =>
                {
                    b.Property<long>("ParqueaderoVisitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("parqueaderovisitanteid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParqueaderoVisitanteId"));

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechahoraingreso");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechahorasalida");

                    b.Property<int>("IngresoId")
                        .HasColumnType("int")
                        .HasColumnName("ingresoid");

                    b.Property<int>("ParqueaderoId")
                        .HasColumnType("int")
                        .HasColumnName("parqueaderoid");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("placa");

                    b.HasKey("ParqueaderoVisitanteId");

                    b.ToTable("parqueaderovisitante", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Reserva", b =>
                {
                    b.Property<long>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reservaid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReservaId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("horafin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("horainicio");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioid");

                    b.Property<int>("ZonaComunId")
                        .HasColumnType("int")
                        .HasColumnName("zonacomunid");

                    b.HasKey("ReservaId");

                    b.ToTable("reserva", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.ResidenteUnidad", b =>
                {
                    b.Property<long>("ResidenteUnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("residenteunidadid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResidenteUnidadId"));

                    b.Property<bool>("EsPropietario")
                        .HasColumnType("bit")
                        .HasColumnName("espropietario");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidadid");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioid");

                    b.HasKey("ResidenteUnidadId");

                    b.ToTable("residenteunidad", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Rol", b =>
                {
                    b.Property<long>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rolid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.ToTable("rol", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.TipoMantenimiento", b =>
                {
                    b.Property<long>("TipoMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tipomantenimientoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TipoMantenimientoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoMantenimientoId");

                    b.ToTable("tipomantenimiento", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Torre", b =>
                {
                    b.Property<long>("TorreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("torreid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TorreId"));

                    b.Property<int>("ConjuntoId")
                        .HasColumnType("int")
                        .HasColumnName("conjuntoid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("TorreId");

                    b.ToTable("torre", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.Usuario", b =>
                {
                    b.Property<long>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usuarioid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechacreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rolid");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.HasKey("UsuarioId");

                    b.ToTable("usuario", "dbo");
                });

            modelBuilder.Entity("BlazorApp1.Client.Models.ZonaComun", b =>
                {
                    b.Property<long>("ZonaComunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("zonacomunid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ZonaComunId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequierePago")
                        .HasColumnType("bit")
                        .HasColumnName("requierepago");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorhora");

                    b.HasKey("ZonaComunId");

                    b.ToTable("zonacomun", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
